# -*- coding: utf-8 -*-
"""Spam Email Classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRhlDOFturb3kwoGhBbPEISQKKtt9iRp
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Load the uploaded dataset (exact path you uploaded)
df = pd.read_csv("/content/drive/MyDrive/spam.csv", encoding="latin-1")

# Keep only needed columns and rename
df = df[['v1', 'v2']]
df.columns = ['label', 'message']

# Show first 5 rows and shape
print(df.shape)
df.head()

import nltk
import re
from nltk.corpus import stopwords

# Download stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()  # lowercase
    text = re.sub(r'[^a-zA-Z]', ' ', text)  # keep only letters
    words = text.split()
    words = [w for w in words if w not in stop_words]  # remove stopwords
    return " ".join(words)

# Apply cleaning
df['clean_message'] = df['message'].apply(clean_text)

df.head()

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(ngram_range=(1,2))
X = vectorizer.fit_transform(df['clean_message'])
y = df['label']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB(alpha=0.1)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, pos_label='spam'))
print("Recall:", recall_score(y_test, y_pred, pos_label='spam'))
print("F1 Score:", f1_score(y_test, y_pred, pos_label='spam'))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Visual Confusion Matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred, labels=['ham', 'spam'])

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['ham', 'spam'],
            yticklabels=['ham', 'spam'])

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix Heatmap")
plt.show()

def predict_message(text):
    cleaned = clean_text(text)
    vector = vectorizer.transform([cleaned])
    prediction = model.predict(vector)[0]
    return "Spam" if prediction == "spam" else "Ham"

samples = [
    "Congratulations! You've won a free lottery. Claim now.",
    "Are you coming to office today?",
    "Free vacation offer only for you!"
]

for msg in samples:
    print("Message:", msg)
    print("Prediction:", predict_message(msg))
    print("-" * 40)